
<div id="ar-widget"
     onclick="requestMic(this);"
     class="ar-tooltip"
     data-tooltip="Do you have something to say about the image or document displayed here? Click here to record your story. You can save the result on your computer, or upload it to improve our collection.">
  <button id="ar-record-btn" title="Record">&#9679;</button>
  <button id="ar-pause-btn" disabled title="Pause">||</button>
  <button id="ar-stop-btn" onclick="stopRecording(this);" disabled>&#9632</button>
  <p id="ar-status">Record your story!</p>
</div>
<h3 id="recordings">Your Current Recordings</h3>
<ul id="recordingslist"></ul>
<pre id="log"></pre>

<script>
 AUDIO_RECORDER_UPLOAD_URL = "<?php echo public_url("items/upload-audio/$this->item_id"); ?>"
 AUDIO_RECORDER_JAVASCRIPT_DIR = "<?php echo public_url("plugins/AudioRecorder/views/shared/javascripts/"); ?>"
</script>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js"></script>
<script src="<?php echo public_url("plugins/AudioRecorder/views/shared/javascripts/init_widget.js") ?>"></script>
<script src="<?php echo public_url("plugins/AudioRecorder/views/shared/javascripts/recordmp3.js"); ?>"></script>



<div id="ar-dialog" style="display:none;">
  <form id="ar-upload-form">
      <?php echo $this->csrf;?>
    <div class="field">
      <div id="ar-title-label" class="two columns alpha">
        <label for="ar-title"><?php echo __('Recording Title:'); ?></label>
      </div>
      <div class="inputs five columns omega">
        <?php echo get_view()->formText('ar-title', ''); ?>
      </div>
        <p class="explanation"><?php echo __('Please enter a short title for your recording'); ?></p>
    </div>

    <div class="field">
      <div id="ar-username-label" class="two columns alpha">
        <label for="ar-username"><?php echo __('Creator name:'); ?></label>
      </div>
      <div class="inputs five columns omega">
        <?php echo get_view()->formText('ar-username', $this->username); ?>
      </div>
        <p class="explanation"><?php echo __('Please enter the preferred name of the person or people whose voice(s) appear on the recording.'); ?></p>
    </div>

    <div class="field">
      <div id="ar-email-label" class="two columns alpha">
        <label for="ar-email"><?php echo __('Email:'); ?></label>
      </div>
      <div class="inputs five columns omega">
        <?php echo get_view()->formText('ar-email', $this->email); ?>
      </div>
        <p class="explanation"><?php echo __('We will keep this address private, and use it only if we have administrative questions about your audio upload.'); ?></p>

    </div>

    <div class="field">
      <div id="ar-researchRights" class="two columns alpha">
        <label for="ar-researchRights"><?php echo __('I agree to the Terms and Conditions:'); ?></label>
      </div>
      <div class="inputs five columns omega">
        <?php 
        echo get_view()->formCheckbox('ar-researchRights','yes',null,array('yes','no')); 
        ?>
      </div>
      <p class="explanation" stlye="font-colour=blue"><a href='/licenseagreement'><?php echo __('In order to contribute, you must read and agree to the Terms and Conditions.'); ?></a></p>
    </div>

    <div class="field">
      <div id="ar-displayRights" class="two columns alpha">
        <label for="ar-displayRights"><?php echo __('Publish my contribution publicly on the web:'); ?></label>
      </div>
      <div class="inputs five columns omega">
        <?php 
        echo get_view()->formCheckbox('ar-displayRights','yes',null,array('yes','no')); 
        ?>
      </div>
    </div>

    <div class="field">
      <div id="ar-anon" class="two columns alpha">
        <label for="ar-anon"><?php echo __('Contribute anonymously:'); ?></label>
      </div>
      <div class="inputs five columns omega">
        <?php 
        echo get_view()->formCheckbox('ar-anon','no',null,array('yes','no')); 
        ?>
      </div>
      <p class="explanation"><?php echo __('Checking this option will display the contributor name as "anonymous"  when displayed publicly.'); ?></p>
    </div>
  </form>
</div>
